// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX3CiXCx5ZW0N3Kh5Jn-VnGJZhSQTRRCw',
    appId: '1:463821131261:web:e2330f002addc9d7911d94',
    messagingSenderId: '463821131261',
    projectId: 'gocab-3ba80',
    authDomain: 'gocab-3ba80.firebaseapp.com',
    storageBucket: 'gocab-3ba80.appspot.com',
    measurementId: 'G-212H0C4M2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAauiGJjg2tlj6fh3QrO72OTDEapd6VHFs',
    appId: '1:463821131261:android:7e76d4d8e731fef2911d94',
    messagingSenderId: '463821131261',
    projectId: 'gocab-3ba80',
    storageBucket: 'gocab-3ba80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJa2kGL77gxxPvn0Vpf191qq81imZ2lvw',
    appId: '1:463821131261:ios:c69a7d3d4c494217911d94',
    messagingSenderId: '463821131261',
    projectId: 'gocab-3ba80',
    storageBucket: 'gocab-3ba80.appspot.com',
    androidClientId: '463821131261-9qfuarhcc6vgg6ohdu95s5nmknlumgf1.apps.googleusercontent.com',
    iosClientId: '463821131261-d3kh74f4t1sooieoi9o1rcel7j7jfeb3.apps.googleusercontent.com',
    iosBundleId: 'com.example.gocab2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJa2kGL77gxxPvn0Vpf191qq81imZ2lvw',
    appId: '1:463821131261:ios:c69a7d3d4c494217911d94',
    messagingSenderId: '463821131261',
    projectId: 'gocab-3ba80',
    storageBucket: 'gocab-3ba80.appspot.com',
    androidClientId: '463821131261-9qfuarhcc6vgg6ohdu95s5nmknlumgf1.apps.googleusercontent.com',
    iosClientId: '463821131261-d3kh74f4t1sooieoi9o1rcel7j7jfeb3.apps.googleusercontent.com',
    iosBundleId: 'com.example.gocab2',
  );
}
